apiVersion: apps/v1
kind: Deployment
metadata:
  name: qingdao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qingdao
  template:
    metadata:
      labels:
        app: qingdao
    spec:
      containers:
      - image: registry.cloud.okteto.net/fromxt/qingdao:python
        name: qingdao

---

apiVersion: v1
kind: Service
metadata:
  name: qingdao
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "qingdao"
    port: 8080
  selector:
    app: qingdao